"""initial schema

Revision ID: 12319bc5429e
Revises: 
Create Date: 2026-07-09 15:56:01.325245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12319bc5429e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('file_sha256', sa.String(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('row_count_total', sa.Integer(), nullable=False),
    sa.Column('row_count_imported', sa.Integer(), nullable=False),
    sa.Column('row_count_excluded_adult', sa.Integer(), nullable=False),
    sa.Column('row_count_excluded_other_type', sa.Integer(), nullable=False),
    sa.Column('row_count_errors', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ranking_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('ranking_year', sa.Integer(), nullable=False),
    sa.Column('source_pdf_path', sa.String(), nullable=False),
    sa.Column('source_pdf_sha256', sa.String(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('enrichment_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ranking_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ranking_cache_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('school_name_raw', sa.String(), nullable=False),
    sa.Column('city_raw', sa.String(), nullable=False),
    sa.Column('voivodeship_raw', sa.String(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['ranking_cache_id'], ['ranking_cache.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ranking_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ranking_entries_ranking_cache_id'), ['ranking_cache_id'], unique=False)

    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rspo_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Enum('PRIMARY', 'LICEUM', 'TECHNIKUM', name='schoollevel'), nullable=False),
    sa.Column('voivodeship', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('ownership_subtype', sa.Enum('NIEPUBLICZNA', 'SPOLECZNA', 'MIEDZYNARODOWA', name='ownershipsubtype'), nullable=True),
    sa.Column('ownership_subtype_verified', sa.Boolean(), nullable=False),
    sa.Column('ownership_subtype_source', sa.Enum('RSPO_NAME_MATCH', 'RSPO_STRUCTURED_FIELD', 'ENRICHMENT', name='evidencesource'), nullable=True),
    sa.Column('student_count', sa.Integer(), nullable=True),
    sa.Column('is_branch', sa.Boolean(), nullable=False),
    sa.Column('has_grades_7_8', sa.Boolean(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('language_orientation', sa.Enum('BILINGUAL', 'ENGLISH_FIRST_PLUS_EXTRA', 'STANDARD_ENGLISH', name='languageorientation'), nullable=True),
    sa.Column('language_orientation_source', sa.Enum('RSPO_NAME_MATCH', 'RSPO_STRUCTURED_FIELD', 'ENRICHMENT', name='evidencesource'), nullable=True),
    sa.Column('school_profile', sa.String(), nullable=True),
    sa.Column('director_name', sa.String(), nullable=True),
    sa.Column('raw_import_row', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_imported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_in_import_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['last_import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schools_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_schools_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_schools_is_private'), ['is_private'], unique=False)
        batch_op.create_index(batch_op.f('ix_schools_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_schools_ownership_subtype'), ['ownership_subtype'], unique=False)
        batch_op.create_index(batch_op.f('ix_schools_rspo_id'), ['rspo_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_schools_student_count'), ['student_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_schools_voivodeship'), ['voivodeship'], unique=False)

    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('from_stage', sa.String(), nullable=True),
    sa.Column('to_stage', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_school_id'), ['school_id'], unique=False)

    op.create_table('enrichment_job_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['enrichment_jobs.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrichment_job_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrichment_job_items_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichment_job_items_school_id'), ['school_id'], unique=False)

    op.create_table('pipeline_state',
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('NOT_CONTACTED', 'CONTACTED', 'RESPONDED', 'MEETING_BOOKED', 'MEETING_HELD', 'NEXT_STEP_AGREED', 'WON', 'LOST', name='pipelinestage'), nullable=False),
    sa.Column('entered_pipeline_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('stage_updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('next_action_note', sa.String(), nullable=True),
    sa.Column('next_action_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('school_id')
    )
    op.create_table('school_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('contact_type', sa.String(), nullable=False),
    sa.Column('person_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('enrichment_job_id', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['enrichment_job_id'], ['enrichment_jobs.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_contacts_school_id'), ['school_id'], unique=False)

    op.create_table('school_ranking_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('ranking_entry_id', sa.Integer(), nullable=False),
    sa.Column('ranking_year', sa.Integer(), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('match_status', sa.String(), nullable=False),
    sa.Column('matched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ranking_entry_id'], ['ranking_entries.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_ranking_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_ranking_matches_school_id'), ['school_id'], unique=False)

    op.create_table('school_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('rubric_type', sa.Enum('PRIMARY', 'SECONDARY', name='rubrictype'), nullable=False),
    sa.Column('rubric_version', sa.String(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('criterion_breakdown', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_scores_school_id'), ['school_id'], unique=False)

    op.create_table('current_scores',
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('rubric_type', sa.Enum('PRIMARY', 'SECONDARY', name='rubrictype'), nullable=False),
    sa.Column('score_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['score_id'], ['school_scores.id'], ),
    sa.PrimaryKeyConstraint('school_id', 'rubric_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current_scores')
    with op.batch_alter_table('school_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_scores_school_id'))

    op.drop_table('school_scores')
    with op.batch_alter_table('school_ranking_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_ranking_matches_school_id'))

    op.drop_table('school_ranking_matches')
    with op.batch_alter_table('school_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_contacts_school_id'))

    op.drop_table('school_contacts')
    op.drop_table('pipeline_state')
    with op.batch_alter_table('enrichment_job_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrichment_job_items_school_id'))
        batch_op.drop_index(batch_op.f('ix_enrichment_job_items_job_id'))

    op.drop_table('enrichment_job_items')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_school_id'))

    op.drop_table('activity_log')
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schools_voivodeship'))
        batch_op.drop_index(batch_op.f('ix_schools_student_count'))
        batch_op.drop_index(batch_op.f('ix_schools_rspo_id'))
        batch_op.drop_index(batch_op.f('ix_schools_ownership_subtype'))
        batch_op.drop_index(batch_op.f('ix_schools_level'))
        batch_op.drop_index(batch_op.f('ix_schools_is_private'))
        batch_op.drop_index(batch_op.f('ix_schools_is_active'))
        batch_op.drop_index(batch_op.f('ix_schools_city'))

    op.drop_table('schools')
    with op.batch_alter_table('ranking_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ranking_entries_ranking_cache_id'))

    op.drop_table('ranking_entries')
    op.drop_table('enrichment_jobs')
    op.drop_table('users')
    op.drop_table('ranking_cache')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
