"""add scope to saved_views

Revision ID: 2598dccc0722
Revises: c1c8151cbe49
Create Date: 2026-07-14 16:01:42.452708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2598dccc0722'
down_revision: Union[str, Sequence[str], None] = 'c1c8151cbe49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scope', sa.String(), nullable=False, server_default='library'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_views', schema=None) as batch_op:
        batch_op.drop_column('scope')

    # ### end Alembic commands ###
