"""add saved views and tags

Revision ID: 26cce350bd8e
Revises: 6f020ccfa0db
Create Date: 2026-07-12 23:24:37.079289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26cce350bd8e'
down_revision: Union[str, Sequence[str], None] = '6f020ccfa0db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('saved_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('filters_json', sa.JSON(), nullable=False),
    sa.Column('sort', sa.String(), nullable=True),
    sa.Column('result_limit', sa.Integer(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'tag_id', name='uq_school_tag')
    )
    with op.batch_alter_table('school_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_tags_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_tags_tag_id'), ['tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_tags_tag_id'))
        batch_op.drop_index(batch_op.f('ix_school_tags_school_id'))

    op.drop_table('school_tags')
    op.drop_table('saved_views')
    op.drop_table('tags')
    # ### end Alembic commands ###
