"""drop schoolscore tier column

Revision ID: 32783bba94e2
Revises: cdaaa78b82d4
Create Date: 2026-07-10 16:29:22.738905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32783bba94e2'
down_revision: Union[str, Sequence[str], None] = 'cdaaa78b82d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_scores', schema=None) as batch_op:
        batch_op.drop_column('tier')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
