"""add is_adult_education

Revision ID: cdaaa78b82d4
Revises: 12319bc5429e
Create Date: 2026-07-09 22:56:14.080947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdaaa78b82d4'
down_revision: Union[str, Sequence[str], None] = '12319bc5429e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_adult_education', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('PRIMARY', 'LICEUM', 'TECHNIKUM', 'BRANZOWA_I', 'BRANZOWA_II', 'POLICEALNA', name='schoollevel'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_schools_is_adult_education'), ['is_adult_education'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schools_is_adult_education'))
        batch_op.alter_column('level',
               existing_type=sa.Enum('PRIMARY', 'LICEUM', 'TECHNIKUM', 'BRANZOWA_I', 'BRANZOWA_II', 'POLICEALNA', name='schoollevel'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
        batch_op.drop_column('is_adult_education')

    # ### end Alembic commands ###
