"""add geo coords, auto enrich settings, job automatic flag

Revision ID: f8872f5a8749
Revises: 26cce350bd8e
Create Date: 2026-07-13 23:11:47.829105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8872f5a8749'
down_revision: Union[str, Sequence[str], None] = '26cce350bd8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_enrich_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schools_per_run', sa.Integer(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_found_count', sa.Integer(), nullable=True),
    sa.CheckConstraint('id = 1', name='ck_auto_enrich_settings_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrichment_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_automatic', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('enrichment_jobs', schema=None) as batch_op:
        batch_op.drop_column('is_automatic')

    op.drop_table('auto_enrich_settings')
    # ### end Alembic commands ###
